import { db } from "./firebase.js";
import { collection, addDoc, getDocs, updateDoc, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js";
import { setHead } from "./app.js";
import { esc, toast } from "./utils.js";
function fileData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
export async function renderFirmen(el,ctx){
  setHead("Firmen","Gesellschaften, Firmenlogos und Grundeinstellungen verwalten.");
  const s=await getDocs(collection(db,"companies")),companies=s.docs.map(d=>({id:d.id,...d.data()}));
  el.innerHTML=`<div class="admin-choice-grid"><button class="choice-card active" data-tab="show"><span>▣</span><strong>Firmen anzeigen</strong><small>Vorhandene Gesellschaften und Logos</small></button><button class="choice-card" data-tab="create"><span>＋</span><strong>Firma anlegen</strong><small>Neue Gesellschaft hinzufügen</small></button></div><section id="company-show"><article class="card"><div class="card-head"><div><h2>Firmenübersicht</h2></div></div>${companies.length?companies.map(c=>`<div class="company-row"><div class="company-thumb">${c.logoDataUrl?`<img src="${c.logoDataUrl}" alt="">`:esc(c.short||'TP')}</div><div><strong>${esc(c.name||'')}</strong><span>${esc(c.short||'')}</span></div><button class="btn secondary small edit-company" data-id="${c.id}">Bearbeiten</button></div>`).join(''):`<div class="empty">Noch keine Firma angelegt.</div>`}</article></section><section id="company-create" class="hidden"><article class="card"><div class="card-head"><div><h2>Firma anlegen / bearbeiten</h2></div></div><form id="company-form" class="form-grid"><input type="hidden" name="id"><label class="field"><span>Firmenname</span><input name="name" required></label><label class="field"><span>Kürzel</span><input name="short" maxlength="12"></label><label class="field full"><span>Firmenlogo</span><input name="logo" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="field full"><p class="muted small">Für V1.0 wird das Logo direkt im Firmen-Datensatz gespeichert. Die vorbereitete Storage-Anbindung an KalkPro kann später ohne Änderung der Benutzerzuordnung ergänzt werden.</p><button class="btn primary">Speichern</button></div></form></article></section>`;
  const show=document.getElementById('company-show'),create=document.getElementById('company-create');
  function tab(t){show.classList.toggle('hidden',t!=='show');create.classList.toggle('hidden',t!=='create');el.querySelectorAll('.choice-card').forEach(x=>x.classList.toggle('active',x.dataset.tab===t))}
  el.querySelectorAll('.choice-card').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
  el.querySelectorAll('.edit-company').forEach(b=>b.onclick=()=>{const c=companies.find(x=>x.id===b.dataset.id),f=document.getElementById('company-form');f.elements.id.value=c.id;f.elements.name.value=c.name||'';f.elements.short.value=c.short||'';tab('create')});
  document.getElementById('company-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,id=f.elements.id.value,data={name:f.elements.name.value.trim(),short:f.elements.short.value.trim(),updatedAt:serverTimestamp()};const file=f.elements.logo.files[0];if(file)data.logoDataUrl=await fileData(file);if(id)await updateDoc(doc(db,'companies',id),data);else await addDoc(collection(db,'companies'),{...data,createdAt:serverTimestamp()});toast('Firma gespeichert.');renderFirmen(el,ctx)};
}
