import { firebaseConfig, db } from "./firebase.js";
import { initializeApp, deleteApp } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signOut as secondarySignOut } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-auth.js";
import { collection, getDocs, doc, setDoc, updateDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js";
import { setHead } from "./app.js";
import { AREA_NAMES, esc, fmtDate, syntheticEmail, ROLE_LABELS, toast } from "./utils.js";

async function createAuthAccount(email,password){const name=`creator-${Date.now()}`,app=initializeApp(firebaseConfig,name),a=getAuth(app);try{const cred=await createUserWithEmailAndPassword(a,email,password);await secondarySignOut(a);return cred.user.uid}finally{await deleteApp(app)}}
export async function renderMitarbeiter(el,ctx){
  setHead("Mitarbeiter","Mitarbeiter anzeigen, anlegen und Personal-/Schulungszuordnungen verwalten.");
  const [uSnap,cSnap,tSnap]=await Promise.all([getDocs(collection(db,'users')),getDocs(collection(db,'companies')),getDocs(collection(db,'trainings'))]);
  const users=uSnap.docs.map(d=>({id:d.id,...d.data()})),companies=cSnap.docs.map(d=>({id:d.id,...d.data()})),trainings=tSnap.docs.map(d=>({id:d.id,...d.data()}));
  const supervisors=users.filter(u=>u.role==='supervisor'||u.role==='admin');
  el.innerHTML=`<div class="admin-choice-grid"><button class="choice-card active" data-tab="show"><span>♙</span><strong>Benutzer anzeigen</strong><small>Alle vorhandenen Mitarbeiter direkt anzeigen</small></button><button class="choice-card" data-tab="create"><span>＋</span><strong>Benutzer anlegen</strong><small>Neuen Mitarbeiter und Zugang anlegen</small></button></div>
  <section id="user-show"><article class="card"><div class="card-head"><div><h2>Benutzerübersicht</h2><p>${users.length} Benutzer vorhanden</p></div></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Firma</th><th>Rolle</th><th>Login</th><th>Bereiche</th><th>Status</th><th></th></tr></thead><tbody>${users.length?users.sort((a,b)=>(a.name||'').localeCompare(b.name||'')).map(u=>`<tr><td><strong>${esc(u.name||'')}</strong></td><td>${esc(companies.find(c=>c.id===u.companyId)?.short||companies.find(c=>c.id===u.companyId)?.name||'–')}</td><td>${esc(ROLE_LABELS[u.role]||u.role||'–')}</td><td>${esc(u.hasRealEmail===false?(u.username||'Benutzername'):(u.email||'–'))}</td><td>${(u.bereiche||[]).map(x=>esc(x)).join(', ')||'–'}</td><td><span class="pill ${u.active===false?'red':'green'}">${u.active===false?'inaktiv':'aktiv'}</span></td><td><button class="btn secondary small edit-user" data-id="${u.id}">Bearbeiten</button></td></tr>`).join(''):`<tr><td colspan="7" class="empty">Noch keine Benutzer angelegt.</td></tr>`}</tbody></table></div></article></section>
  <section id="user-create" class="hidden"><article class="card"><div class="card-head"><div><h2>Benutzer anlegen / bearbeiten</h2><p>Mitarbeiterstammdaten und Schulungszuordnung in einem Formular</p></div></div><form id="user-form" class="form-grid"><input type="hidden" name="id"><label class="field"><span>Name</span><input name="name" required></label><label class="field"><span>Firma</span><select name="companyId" required><option value="">– auswählen –</option>${companies.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label>
  <label class="field"><span>Login-Art</span><select name="loginType"><option value="email">E-Mail-Adresse</option><option value="username">Benutzername</option></select></label><label class="field"><span>E-Mail / Benutzername</span><input name="login" required></label><label class="field"><span>Startpasswort</span><input name="password" type="text" placeholder="nur bei Neuanlage"></label><label class="field"><span>Rolle</span><select name="role"><option value="employee">Mitarbeiter</option><option value="supervisor">Vorgesetzter</option><option value="admin">Personalabteilung / Admin</option></select></label>
  <label class="field"><span>Vorgesetzter</span><select name="supervisorId"><option value="">Kein Vorgesetzter</option>${supervisors.map(u=>`<option value="${u.id}">${esc(u.name||u.email)}</option>`).join('')}</select></label><label class="field"><span>Status</span><select name="active"><option value="true">aktiv</option><option value="false">inaktiv</option></select></label><label class="field"><span>Eintritt</span><input name="startDate" type="date"></label><label class="field"><span>Austritt</span><input name="endDate" type="date"></label><label class="field"><span>Wochenstunden</span><input name="weeklyHours" type="number" step="0.25" value="40"></label><label class="field"><span>Urlaubstage/Jahr</span><input name="vacationDays" type="number" step="1" value="30"></label>
  <div class="field full"><span>Schulungsbereiche</span><div class="check-grid">${Object.entries(AREA_NAMES).map(([id,n])=>`<label><input type="checkbox" name="bereich" value="${id}"><span><b>Bereich ${id}</b>${esc(n)}</span></label>`).join('')}</div></div>
  <div class="field full"><span>Individuelle Zusatzschulungen</span><div class="check-grid compact">${trainings.length?trainings.map(t=>`<label><input type="checkbox" name="extraTraining" value="${t.id}"><span>${esc(t.title)}</span></label>`).join(''):'<div class="muted">Noch keine Schulungen vorhanden.</div>'}</div></div>
  <div class="field full actions"><button class="btn primary" type="submit">Benutzer speichern</button><button class="btn secondary" id="cancel-user" type="button">Abbrechen</button></div><p id="user-message" class="message field full"></p></form></article></section>`;
  const show=el.querySelector('#user-show'),create=el.querySelector('#user-create'),form=el.querySelector('#user-form');
  function tab(t){show.classList.toggle('hidden',t!=='show');create.classList.toggle('hidden',t!=='create');el.querySelectorAll('.choice-card').forEach(x=>x.classList.toggle('active',x.dataset.tab===t))}el.querySelectorAll('.choice-card').forEach(b=>b.onclick=()=>{if(b.dataset.tab==='create')form.reset();tab(b.dataset.tab)});
  el.querySelector('#cancel-user').onclick=()=>tab('show');
  el.querySelectorAll('.edit-user').forEach(b=>b.onclick=()=>{const u=users.find(x=>x.id===b.dataset.id);form.reset();form.elements.id.value=u.id;form.elements.name.value=u.name||'';form.elements.companyId.value=u.companyId||'';const usernameMode=u.hasRealEmail===false||String(u.email||'').endsWith('@portal.local');form.elements.loginType.value=usernameMode?'username':'email';form.elements.login.value=usernameMode?(u.username||String(u.email||'').replace(/@portal\.local$/,'')):(u.email||'');form.elements.role.value=u.role||'employee';form.elements.supervisorId.value=u.supervisorId||'';form.elements.active.value=String(u.active!==false);form.elements.startDate.value=u.startDate||'';form.elements.endDate.value=u.endDate||'';form.elements.weeklyHours.value=u.weeklyHours||40;form.elements.vacationDays.value=u.vacationDays||30;form.querySelectorAll('[name=bereich]').forEach(x=>x.checked=(u.bereiche||[]).includes(x.value));form.querySelectorAll('[name=extraTraining]').forEach(x=>x.checked=(u.extraTrainings||[]).includes(x.value));tab('create')});
  form.onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,id=f.elements.id.value,loginType=f.elements.loginType.value,login=f.elements.login.value.trim(),password=f.elements.password.value;const email=loginType==='username'?syntheticEmail(login):login.toLowerCase();const data={name:f.elements.name.value.trim(),companyId:f.elements.companyId.value,email,username:loginType==='username'?login.toLowerCase():'',hasRealEmail:loginType==='email',role:f.elements.role.value,supervisorId:f.elements.supervisorId.value||null,active:f.elements.active.value==='true',startDate:f.elements.startDate.value||null,endDate:f.elements.endDate.value||null,weeklyHours:Number(f.elements.weeklyHours.value||40),vacationDays:Number(f.elements.vacationDays.value||30),bereiche:[...f.querySelectorAll('[name=bereich]:checked')].map(x=>x.value),extraTrainings:[...f.querySelectorAll('[name=extraTraining]:checked')].map(x=>x.value),updatedAt:serverTimestamp()};try{if(id){await updateDoc(doc(db,'users',id),data)}else{if(!password||password.length<6)throw new Error('Für neue Benutzer wird ein Startpasswort mit mindestens 6 Zeichen benötigt.');const uid=await createAuthAccount(email,password);await setDoc(doc(db,'users',uid),{...data,createdAt:serverTimestamp()})}toast('Benutzer gespeichert.');renderMitarbeiter(el,ctx)}catch(err){console.error(err);el.querySelector('#user-message').textContent=err.message||'Benutzer konnte nicht gespeichert werden.'}};
}
