// Automatisch aus den statischen UI-Texten der V2.11.1 erzeugte Positivliste.
// Nur Texte aus dieser Liste dürfen über die Browser-Translator-API automatisch übersetzt werden.
export const SYSTEM_TEXTS = new Set([
  "+ Nachträgliche Zeiterfassung beantragen",
  "+ fünfstellige Mitarbeiternummer. Die Pause wird pro Tag einmal ermittelt und anteilig auf die Projektzeiten verteilt.",
  ". Jahr/Monat stammen aus der gewählten Buchungsperiode, die Kalenderwoche aus dem Erstellungsdatum der CSV.",
  "1. Vorgesetzter",
  "2. Vorgesetzter",
  "Abrechnung gelöscht.",
  "Abrechnung konnte nicht gelöscht werden.",
  "Abrechnung konnte nicht geöffnet werden.",
  "Abrechnung(en)",
  "Abrechnungen anzeigen",
  "Abrechnungen hochladen",
  "Abrechnungsrelevante Schlüssel können selbst gepflegt werden.",
  "Abschließen",
  "Abteilung / Bereich",
  "Abwesenheit buchen",
  "Abwesenheit gebucht.",
  "Abwesenheit gelöscht.",
  "Abwesenheiten / Krankheit buchen",
  "Admins mit der Berechtigung „Mitarbeiternotizen“ sehen alle Einträge. Vorgesetzte sehen ausschließlich ihre eigenen Notizen.",
  "Aktive Mitarbeiter",
  "Aktivierung erneuern",
  "Aktivierungscode konnte nicht erneuert werden.",
  "Aktuell liegen keine Hinweise vor.",
  "Aktuell sind keine HR-Fristen in den vorgesehenen Vorlaufzeiträumen fällig.",
  "Aktuelle Informationen der Personalabteilung",
  "Aktuelle Woche",
  "Aktueller Buchungstext",
  "Aktueller Monat",
  "Alle Firmen",
  "Alle Jahre",
  "Alle Monate",
  "Alle Nachweise",
  "Alle vorhandenen Mitarbeiter direkt anzeigen",
  "Als Dashboard-Hinweis speichern",
  "Als Textbaustein speichern",
  "Antrag ablehnen",
  "Antrag bearbeitet.",
  "Antrag senden",
  "Antrag wird dem zugeordneten Vorgesetzten bereitgestellt.",
  "Antrag wurde als abgelehnt abgeschlossen.",
  "Antrag wurde gesendet.",
  "Antrag zurückziehen",
  "Anträge zur Zeiterfassung",
  "Anträge zur Zeiterfassung freigeben",
  "Anwesenheiten prüfen, Wochenplanung erstellen oder Jahresansicht eines Mitarbeiters öffnen.",
  "Arbeitsmedizinische Vorsorgen / Hinweise",
  "Arbeitszeit bis",
  "Arbeitszeit stempeln",
  "Arbeitszeit von",
  "Arbeitszeit wird frühestens ab",
  "Arbeitszeitbuchungen des zugeordneten Mitarbeiters. Nur Lesezugriff.",
  "Archiv prüfen, filtern und verwalten",
  "Aufgabe 1",
  "Aufgabe 2",
  "Aufgabe 3",
  "Aus dem Präfix",
  "Auswertung anzeigen",
  "Auszahlung von Überstunden",
  "Automatisch aus den Fristdaten der aktiven Mitarbeiter · Vorschau auf die nächsten  Tage",
  "Automatisch: PeriodeJahr/MonatKW",
  "Automatische Variante:",
  "Backup gelöscht.",
  "Backup jetzt erstellen",
  "Backups konnten nicht geladen werden.",
  "Backups werden geladen …",
  "Bank gelöscht.",
  "Bank gespeichert.",
  "Bank wirklich löschen? Bereits gespeicherte Mitarbeiterdaten bleiben als ID erhalten.",
  "Bankname und BIC können zentral gepflegt werden.",
  "Bearbeitungsstand und Nachweise dieses Schulungsjahres.",
  "Bearbeitungsstände und vorhandene Schulungsnachweise des gewählten Jahres",
  "Befristung bis",
  "Befristung endet",
  "Begründung *",
  "Begründung:",
  "Bei 'Sonstiges' ist eine Erläuterung erforderlich.",
  "Bei Benutzernamen erfolgt der Passwort-Reset derzeit über die Personalabteilung.",
  "Bei einem Projektwechsel neue Projektnummer eingeben und erneut",
  "Beides einmalig auf dem Tablet eingeben.",
  "Beispiele: Auszahlung von Überstunden, Übertrag/Korrektur oder Umwandlung eines Urlaubstages. Die Buchung ersetzt keine Kommen-/Gehen-Zeit und bleibt in der Buchungsliste nachvollziehbar.",
  "Bemerkung / Erläuterung",
  "Benutzer anlegen",
  "Benutzer anzeigen",
  "Benutzerübersicht",
  "Bereich wird geladen …",
  "Bereits gestempelte Zeiten können nicht direkt geändert werden. Für jede nachträgliche Änderung ist eine Begründung erforderlich.",
  "Beschreibung für dieses Terminal:",
  "Beschäftigt seit",
  "Beschäftigungsart",
  "Betriebsnummer / Kennung",
  "Bewerbungsportal öffnen",
  "Bitte Arbeitszeit von und bis angeben.",
  "Bitte Google Chrome auf einem NFC-fähigen Android-Gerät verwenden.",
  "Bitte Mitarbeiter und gültiges Jahr auswählen.",
  "Bitte Monatsgehalt und/oder Stundenlohn eingeben.",
  "Bitte Titel und Text eingeben.",
  "Bitte das Datum „Gültig ab“ angeben.",
  "Bitte den Code jetzt am Tablet verwenden. Bei Verlust kann jederzeit ein neuer erzeugt werden.",
  "Bitte die Stammdaten korrigieren. Die CSV wird erst erzeugt, wenn alle betroffenen Projektzeiten vollständig zugeordnet sind.",
  "Bitte ein Datum für die Notiz angeben.",
  "Bitte ein gültiges Jahr auswählen.",
  "Bitte eine Stunden- oder Minutenanzahl größer 0 eingeben.",
  "Bitte eine sechsstellige Projektnummer eingeben.",
  "Bitte einen Mitarbeiter auswählen.",
  "Bitte einen Notiztext eingeben.",
  "Bitte gültigen Monat und Jahr auswählen.",
  "Bitte keine Diagnosen oder medizinischen Details eintragen. Für die Zeitwirtschaft genügt die Art und Dauer der Abwesenheit.",
  "Bitte mindestens eine PDF-Datei auswählen.",
  "Bitte wählen",
  "Bitte zuerst die E-Mail-Adresse eintragen.",
  "Bitte zuerst eine Datei auswählen.",
  "Brandschutzhelfer · Auffrischung",
  "Bruttogehalt / Monat (€)",
  "Buchung(en) können nicht exportiert werden.",
  "Buchungen werden geladen …",
  "Buchungstext-Ergänzung",
  "Buchungstext-Präfix",
  "CSV für PDS herunterladen",
  "CSV nicht erstellt: Bitte zuerst die angezeigten Stammdatenfehler korrigieren.",
  "Das Bewerbungsportal wird später als separates Tool angebunden.",
  "Das Datum wird nur verwendet, wenn sich Schulungsbereiche oder Zusatzschulungen ändern. Frühere Schulungsjahre und Bearbeitungsstände bleiben unverändert.",
  "Das Druckfenster wurde vom Browser blockiert.",
  "Das Kostenarten-Präfix muss genau zweistellig numerisch sein.",
  "Das Passwort ist zu kurz.",
  "Dashboard-Hinweis gespeichert.",
  "Datei hochladen",
  "Dateiauswahl geändert. Bitte die Zuordnung erneut prüfen.",
  "Dateigröße",
  "Datensicherung / Wiederherstellung",
  "Datensicherung abgeschlossen.",
  "Datensicherung erfolgreich erstellt.",
  "Datensicherung fehlgeschlagen.",
  "Datierte Vergütungsentwicklung des zugeordneten Mitarbeiters. Nur Lesezugriff.",
  "Den NFC-Transponder dieses Mitarbeiters wirklich sperren?",
  "Der Antrag konnte nicht bearbeitet werden.",
  "Der Bereich konnte nicht geladen werden.",
  "Der Bis-Termin liegt vor dem Von-Termin.",
  "Der NFC-Transponder kann nach dem Anlegen des Mitarbeiters zugewiesen werden.",
  "Der Transponder ist jetzt für die Terminal-Zeiterfassung freigeschaltet.",
  "Der bisherige NFC-Transponder kann nicht mehr zum Stempeln verwendet werden.",
  "Der bisherige NFC-Transponder wird nach erfolgreicher Zuweisung gesperrt. Fortfahren?",
  "Die Arbeitszeit läuft bereits. Bitte zuerst GEHEN stempeln.",
  "Die Bereiche sind fachlich getrennt. Sensible Steuer-, Bank- und Entgeltdaten sind besonders geschützt.",
  "Die Buchungen konnten nicht geladen werden. Bitte die Zeit-Berechtigungen dieses Adminzugangs prüfen.",
  "Die Buchungen können nach dem Öffnen eines Mitarbeiters angezeigt werden.",
  "Die Datei ist größer als 10 MB.",
  "Die Datensicherung steht ausschließlich der Personalabteilung/Admin zur Verfügung.",
  "Die Dokumente sind ausschließlich für Dich und die Personalabteilung sichtbar.",
  "Die Endzeit muss nach der Startzeit liegen.",
  "Die Firmennummer muss genau zweistellig numerisch sein.",
  "Die Geschäftsbereich-Nr. muss genau dreistellig numerisch sein.",
  "Die Geschäftsbereichsnummer muss exakt dreistellig numerisch sein. Beispiele aus dem KTR-Konzept sind 010 Flächenheizung, 040 Elektrotechnik oder 090 Personal-Dienstleistungen.",
  "Die Historie protokolliert Neuanlagen und Änderungen an Mitarbeiterstammdaten. Passwörter werden nicht gespeichert.",
  "Die KTR-Geschäftsbereiche sind bereits vorhanden.",
  "Die Personalabteilung kann über",
  "Die Projektnummer muss genau sechs Ziffern enthalten.",
  "Die Schulungsdaten konnten nicht geladen werden.",
  "Die Schulungsdefinitionen sind jahresunabhängige Stammdaten. Die Jahresauswahl wirkt auf Zuordnungen, Bearbeitungsstände und Nachweise.",
  "Die Sicherung wird unter einem eigenen, datierten Ordner im KalkPro-Storage abgelegt. Je nach Anzahl und Größe der Dokumente kann der Vorgang einige Minuten dauern.",
  "Die Vergütungshistorie konnte nicht geladen werden.",
  "Die Zeitbuchungen konnten nicht geladen werden.",
  "Die dreistellige Nummer fließt in die PDS-Kostenträgernummer ein und wird dem Mitarbeiter zugeordnet.",
  "Die sichtbare Bezeichnung wird automatisch fortlaufend vergeben.",
  "Die tatsächliche Uhrzeit wird beim Klick automatisch übernommen.",
  "Diese Abwesenheitsbuchung wirklich löschen?",
  "Diese Adresse auf jedem Android-Tablet in Chrome öffnen und anschließend zum Startbildschirm hinzufügen.",
  "Diese Dokumente werden über den Sammelupload im Bereich Lohn-/Gehaltsabrechnung bereitgestellt.",
  "Diese Einträge stehen in der Mitarbeiterkartei als Dropdown zur Verfügung.",
  "Diese Geschäftsbereich-Nr. ist bereits vorhanden.",
  "Diese Planung wirklich löschen?",
  "Diesen Code einmalig auf dem betreffenden Tablet eingeben. Er wird aus Sicherheitsgründen nicht im Klartext gespeichert.",
  "Diesen Urlaubsantrag wirklich zurückziehen? Der Vorgang bleibt dokumentiert und der Vorgesetzte wird informiert.",
  "Dieser Bereich bleibt modular erweiterbar.",
  "Dieser Bereich ist ausschließlich für die Personalabteilung / Admins vorgesehen.",
  "Dieser Schlüssel ist bereits vorhanden.",
  "Digitale Mitarbeiterkartei",
  "Digitale Personalakte",
  "Direkt durch die Personalabteilung erfasste Fehlzeiten.",
  "Dokument gelöscht.",
  "Dokument hochgeladen.",
  "Dokument hochladen",
  "Dokument konnte nicht gelöscht werden.",
  "Dokument konnte nicht geöffnet werden.",
  "Dokumente können nach dem erstmaligen Speichern des Mitarbeiters hochgeladen werden.",
  "Download nicht möglich.",
  "Drucken / PDF",
  "E-Mail / Benutzername",
  "E-Mail versenden",
  "E-Mail wurde versendet.",
  "Eigene interne Notizen zu diesem Mitarbeiter. Andere Vorgesetzten- oder Admin-Notizen sind nicht sichtbar.",
  "Eine Begründung ist erforderlich.",
  "Eine Wiederherstellung überschreibt die gesicherten Anwendungsdaten mit dem Stand des gewählten Backups. Neue Historieneinträge werden aus Gründen der Nachvollziehbarkeit nicht gelöscht.",
  "Einträge",
  "Einträge verwalten",
  "Empfänger, Betreff und Text werden benötigt.",
  "Empfänger-E-Mail-Adressen",
  "Erledigte Anträge bleiben als Nachweis erhalten.",
  "Erstellt einen vollständigen serverseitigen Sicherungsstand.",
  "Erstellt von",
  "Ersthelfer · Auffrischung",
  "Es besteht bereits ein offener Antrag vom . Ein weiterer Antrag ist erst nach Bearbeitung möglich.",
  "Es werden nur tatsächlich geänderte Felder an die Personalabteilung übermittelt.",
  "Es wurden keine Änderungen erkannt.",
  "Feiertage: bundesweit geltende Feiertage. Regionale Feiertage werden in V2.2 noch nicht automatisch ergänzt.",
  "Firestore-Daten und Dateien werden gesichert. Bitte dieses Fenster geöffnet lassen.",
  "Firestore-Datensätze und  Dateien () wurden gesichert.",
  "Firma anlegen",
  "Firma anlegen / bearbeiten",
  "Firma gespeichert.",
  "Firmen anzeigen",
  "Firmen verwalten",
  "Firmenübersicht",
  "Foto entfernen",
  "Foto nach dem ersten Speichern möglich",
  "Foto wird hochgeladen …",
  "Freier Text",
  "Freier Zusatztext",
  "Freigaben Zeiterfassung",
  "Freigegebene Kontaktdaten des zugeordneten Mitarbeiters. Nur Lesezugriff.",
  "Frühester anrechenbarer Arbeitsbeginn",
  "Führerscheinklassen",
  "Führerscheinkontrolle",
  "Für  sind Ihnen keine Schulungen zugeordnet.",
  "Für  sind keine Buchungen vorhanden.",
  "Für V1.0 wird das Logo direkt im Firmen-Datensatz gespeichert. Die vorbereitete Storage-Anbindung an KalkPro kann später ohne Änderung der Benutzerzuordnung ergänzt werden.",
  "Für die Geburtstagsliste sind derzeit keine Mitarbeiter freigegeben.",
  "Für diese Buchungsperiode liegen keine abgeschlossenen projektbezogenen Buchungen vor.",
  "Für diesen Admin-Zugang ist die Terminalverwaltung nicht freigeschaltet.",
  "Für diesen Admin-Zugang ist die Verwaltung von Lohn-/Gehaltsabrechnungen nicht freigeschaltet.",
  "Für diesen Admin-Zugang ist keine Berechtigung zur Mitarbeiterverwaltung freigeschaltet.",
  "Für diesen Admin-Zugang ist keine Schulungsübersicht oder Schulungsverwaltung freigeschaltet.",
  "Für diesen Benutzer ist kein Vorgesetzter hinterlegt. Der Antrag kann derzeit nicht weitergeleitet werden.",
  "Für diesen Tag existiert bereits eine Buchung. Möchten Sie trotzdem einen Antrag zur nachträglichen Erfassung stellen? Bei einer fehlerhaften Buchung ist normalerweise ‚Korrektur beantragen‘ die bessere Wahl.",
  "Für dieses Jahr sind keine Krankheitstage erfasst.",
  "Für dieses Schulungsjahr ist noch kein Bearbeitungsstand vorhanden.",
  "Gebuchte Abwesenheiten",
  "Geburtstage & Jubiläen",
  "Geburtstage 7 Tage im Voraus · Betriebsjubiläen 30 Tage im Voraus",
  "Geburtstagsliste ja",
  "Gehen konnte nicht gespeichert werden.",
  "Gemeldet / zu übernehmen",
  "Genehmigter Urlaub",
  "Geplante Arbeitszeiten und Aufgaben. Diese Planung ist keine Arbeitszeitbuchung und verändert weder Stundenkonto noch Zeiterfassung.",
  "Geplanter Austritt",
  "Geprüft und Mitarbeiterakte aktualisieren",
  "Geprüfte Abrechnungen hochladen",
  "Geschäftsbereich",
  "Geschäftsbereich gelöscht.",
  "Geschäftsbereich gespeichert.",
  "Geschäftsbereich wirklich löschen? Bereits gespeicherte Mitarbeiterzuordnungen bleiben erhalten.",
  "Geschäftsbereich-Nr.",
  "Geschäftsbereiche",
  "Geschäftsbereiche aus KTR-Konzept übernehmen",
  "Gesicherte Stände des TP-Personalmanagements.",
  "Gespeicherte Arbeitszeiten und Stundenkorrekturen. „Zeitguthaben“ zeigt den minutengenauen Stand des Stundenkontos nach der jeweiligen Buchung.",
  "Gespeicherte Dashboard-Meldungen",
  "Gespeicherte Hinweise",
  "Gewünschter Beginn",
  "Gewünschtes Ende",
  "Geändert von",
  "Geöffnet",
  "Geöffnet:  · Abgeschlossen:  · Nachweis:",
  "Groß",
  "Grund der Ablehnung / Hinweis an den Mitarbeiter:",
  "Gültig ab",
  "HR-Erinnerungen & Fristen",
  "Heirat am",
  "Heute abwesend",
  "Hinweis an die Personalabteilung",
  "Hinweis wirklich löschen?",
  "Hinweis: Skalierung auf 73 % einstellen und „Hintergrundgrafiken“ aktivieren.",
  "Hinweise anzeigen",
  "Hubarbeitsbühne",
  "Hubarbeitsbühne läuft ab",
  "Ihnen sind aktuell keine Mitarbeiter direkt zugeordnet.",
  "Individuelle Zusatzschulungen",
  "Interne Bemerkung",
  "Jahresauswertung als Mitarbeiterliste und Säulendiagramm.",
  "Jahresübersicht Anwesenheit",
  "Jetzt einen vollständigen Sicherungsstand des TP-Personalmanagements erstellen?",
  "KW  ·",
  "Kein Vorgesetzter",
  "Kein zweiter Vorgesetzter",
  "Keine Abrechnungen für den gewählten Filter.",
  "Keine Anträge vorhanden.",
  "Keine Aufgabe hinterlegt",
  "Keine Berechtigung für News & Hinweise.",
  "Keine Berechtigung für Stammdaten-Änderungsanträge.",
  "Keine Berechtigung zum Anlegen von Admin-Zugängen.",
  "Keine Berechtigung zum Anlegen von Mitarbeitern.",
  "Keine Berechtigung zum Bearbeiten von Mitarbeitern.",
  "Keine Berechtigung zum Entfernen von Mitarbeitern.",
  "Keine Berechtigung zum Ändern von Admin-Rollen.",
  "Keine Berechtigung zur Firmenverwaltung.",
  "Keine Berechtigung.",
  "Keine Daten für den Export vorhanden.",
  "Keine Hinweise vorhanden.",
  "Keine Mitarbeiter gefunden.",
  "Keine Mitarbeiter vorhanden.",
  "Keine Schulungen vorhanden.",
  "Keine gültigen Abrechnungen zum Hochladen vorhanden.",
  "Keine offenen Freigaben.",
  "Keine Änderungsanträge vorhanden.",
  "Kind krank",
  "Kommen / Projektwechsel konnte nicht gespeichert werden.",
  "Kontaktdaten und Zeitbuchungen konnten nicht geladen werden.",
  "Kontaktdaten und Zeitbuchungen werden geladen …",
  "Kontrolle nach Firma, Abrechnungsmonat und Mitarbeiter.",
  "Korrektur beantragen",
  "Korrekturantrag wurde gesendet.",
  "Kostenart und Buchungstext einstellen",
  "Kostenarten-Präfix Personal",
  "Kostenträger",
  "Krankenkasse gelöscht.",
  "Krankenkasse gespeichert.",
  "Krankenkasse wirklich löschen? Bereits gespeicherte Mitarbeiterdaten bleiben als ID erhalten.",
  "Krankheit und weitere Abwesenheiten direkt durch die Personalabteilung erfassen.",
  "Krankheitstage gesamt",
  "Krankheitstage nach Monaten ·",
  "Kürzel",
  "Letzte Korrekturbuchungen",
  "Letzte Nutzung",
  "Liste anzeigen",
  "Lohn & Gehalt – Historie",
  "Lohn-/Gehaltsabrechnungen verwalten",
  "Löschen",
  "Manuelle Einsatzplanung",
  "Maximal 10 MB.",
  "Mehrere PDF-Dateien automatisch zuordnen",
  "Mehrfachauswahl möglich · max. 10 MB je PDF",
  "Mein Bearbeitungsstand",
  "Mein Bearbeitungsstand ·",
  "Mein Status",
  "Meine Anträge",
  "Meine Buchungen",
  "Meine Lohn-/Gehaltsabrechnungen",
  "Meine Mitarbeiter",
  "Meine Schulungen",
  "Meine Änderungsanträge",
  "Minuten müssen zwischen 0 und 59 liegen.",
  "Mitarbeiter anlegen",
  "Mitarbeiter bearbeiten",
  "Mitarbeiter entfernen",
  "Mitarbeiter gespeichert.",
  "Mitarbeiter mit Krankheitstagen",
  "Mitarbeiter speichern",
  "Mitarbeiter suchen",
  "Mitarbeiter und Jahr auswählen, Jahresübersicht anzeigen und drucken bzw. als PDF speichern.",
  "Mitarbeiter und Jahr auswählen.",
  "Mitarbeiter wurde entfernt und der Zugang deaktiviert.",
  "Mitarbeiter wurde neu angelegt.",
  "Mitarbeiter zuerst anlegen bzw. öffnen.",
  "Mitarbeiter zuerst öffnen.",
  "Mitarbeiter-Historie anzeigen",
  "Mitarbeiterakte wurde aktualisiert.",
  "Mitarbeiterfoto entfernt.",
  "Mitarbeiterfoto gespeichert.",
  "Mitarbeiterfoto wirklich entfernen?",
  "Mitarbeiterkartei öffnen",
  "Mitarbeiternotizen einsehen / verwalten",
  "Mitteilung erstellen",
  "Mitteilung erstellen und optional versenden",
  "Monat und Jahr einmal auswählen. Die Mitarbeiterzuordnung erfolgt anschließend über die Mitarbeiternummer im PDF-Dateinamen.",
  "Monatsgehalt und Stundenlohn können gleichzeitig gepflegt werden. „Übernehmen“ legt einen unveränderlichen Historieneintrag an.",
  "NFC-Terminals & Transponder verwalten",
  "NFC-Transponder wurde gesperrt.",
  "NFC-Transponder zugewiesen",
  "Nach Monaten sortierte Liste aller Mitarbeiter, die der Aufnahme in die Geburtstagsliste zugestimmt haben.",
  "Nachträgliche Erfassungen und Korrekturen werden erst nach Freigabe wirksam.",
  "Nachträgliche Zeiterfassung beantragen",
  "Nachweis hochladen",
  "Nachweis konnte nicht geladen werden.",
  "Nachweise je Mitarbeiter",
  "Nachweise je Mitarbeiter ·",
  "Name der Krankenkasse",
  "Neue Datensicherung",
  "Neue Gesellschaft hinzufügen",
  "Neue Mitarbeiterkartei und Zugang anlegen",
  "Neue Schulung und Bereichszuordnung",
  "Neue Schulungszuordnung gültig ab",
  "Neuer Aktivierungscode wurde erzeugt.",
  "Neues Passwort (mindestens 6 Zeichen):",
  "Neues Terminal",
  "News & Hinweise",
  "News & Hinweise verwalten",
  "News / E-Mail erstellen",
  "Noch kein Terminal angelegt.",
  "Noch keine Abwesenheiten gebucht.",
  "Noch keine Banken hinterlegt.",
  "Noch keine Bearbeitungsstände in diesem Jahr.",
  "Noch keine Benutzer angelegt.",
  "Noch keine Buchungen vorhanden.",
  "Noch keine Dateien ausgewählt und geprüft.",
  "Noch keine Datensicherung vorhanden.",
  "Noch keine Firma angelegt.",
  "Noch keine Geschäftsbereiche hinterlegt.",
  "Noch keine Krankenkassen hinterlegt.",
  "Noch keine Lohn-/Gehaltsabrechnungen bereitgestellt.",
  "Noch keine Lohn-/Gehaltsabrechnungen hinterlegt.",
  "Noch keine Notizen vorhanden.",
  "Noch keine Religions-/Kirchensteuerschlüssel hinterlegt.",
  "Noch keine Schulungen vorhanden.",
  "Noch keine Stundenkorrekturen gebucht.",
  "Noch keine Vergütungshistorie vorhanden.",
  "Noch keine Zeitanträge vorhanden.",
  "Noch keine eigenen Notizen vorhanden.",
  "Noch keine sonstigen Dokumente in der Personalakte.",
  "Noch keine Änderungen protokolliert.",
  "Noch keine Änderungsanträge vorhanden.",
  "Notiz übernommen.",
  "Notizen konnten nicht geladen werden.",
  "Notizen werden geladen …",
  "Nur Anzeige",
  "Nur bei Rolle „Personalabteilung / Admin“. Bestehende Admins besitzen nach dem Update zunächst alle Rechte.",
  "Nur bei Zustimmung wird der Geburtstag in der Geburtstagsliste ausgegeben.",
  "Nur für Tage, an denen keine vollständige Stempelung vorliegt.",
  "Nur für den Fall einer notwendigen Rücksicherung.",
  "Nächste Führerscheinkontrolle",
  "Nächste Woche ›",
  "Nächster Monat →",
  "Nächstes Terminal anlegen",
  "Offene Anträge .",
  "Offene Anträge der zugeordneten Mitarbeiter sowie zurückgezogene Anträge zur Kenntnisnahme.",
  "Offene Schulungen",
  "Offene Urlaubsanträge",
  "Offene Urlaubsfreigaben",
  "Optional. Bei Eingabe sind genau sechs Ziffern erforderlich.",
  "Optional. Beide Vorgesetzte erhalten dieselben organisatorischen Zugriffsrechte.",
  "Optional. Ein früherer echter KOMMEN-Stempel bleibt sichtbar, wird aber erst ab dieser Uhrzeit angerechnet.",
  "PDF, Office-Dokumente sowie JPG/PNG/WEBP · max. 10 MB",
  "PDS-CSV wurde erstellt.",
  "PDS-Einstellungen speichern",
  "PDS-Exporteinstellungen gespeichert.",
  "PDS-Stundenexport / Auswertungen",
  "PDS-Vorschau erzeugen",
  "Parameter, die bei jedem Stundenexport automatisch verwendet werden.",
  "Passwort geändert.",
  "Passwort konnte nicht geändert werden. Ggf. erneut anmelden.",
  "Passwort-Link konnte nicht angefordert werden.",
  "Passwort-Link wurde angefordert.",
  "Personalabteilung / Admin",
  "Personalakten-Dokumente verwalten",
  "Persönliche Daten & Kontakt",
  "Persönliche Daten ändern",
  "Planung konnte nicht gelöscht werden.",
  "Planung löschen",
  "Planung speichern",
  "Planung wird geladen …",
  "Planung wurde gelöscht.",
  "Position / Tätigkeit",
  "Priorität",
  "Private E-Mail",
  "Probezeit bis",
  "Probezeit endet",
  "Projektnummer *",
  "Projektzeiten automatisch im vorgegebenen 16-spaltigen PDS-Importformat erzeugen.",
  "Regelmäßige Arbeitstage",
  "Religion / Kirchensteuer",
  "Religion / Kirchensteuer gespeichert.",
  "Religions-/Kirchensteuerschlüssel gelöscht.",
  "Religions-/Kirchensteuerschlüssel wirklich löschen? Bereits gespeicherte Mitarbeiterwerte bleiben erhalten.",
  "Rest (ohne Übertrag)",
  "Resturlaub aller aktiven Mitarbeiter für ein ausgewähltes Jahr anzeigen und drucken. Ein separater Vorjahresübertrag wird derzeit nicht geführt.",
  "Resturlaub gesamt:  Tage",
  "Rollen & Admin-Berechtigungen verwalten",
  "Rückmeldung:",
  "Rücknahme zur Kenntnis genommen.",
  "Sammeldownload nicht möglich.",
  "Sammelupload Lohn-/Gehaltsabrechnungen",
  "Schließen",
  "Schlüssel",
  "Schlüssel und Bezeichnung sind erforderlich.",
  "Schulung anlegen",
  "Schulung gespeichert.",
  "Schulung speichern",
  "Schulung wirklich löschen?",
  "Schulung öffnen",
  "Schulungen anzeigen",
  "Schulungen verwalten",
  "Schulungen werden geladen …",
  "Schulungsübersichten / Nachweise",
  "Sehr groß",
  "Sie sehen ausschließlich Ihre eigenen Notizen zu diesem Mitarbeiter.",
  "Soll / Ist ·",
  "Stammdaten ändern",
  "Stammdaten-Änderungsanträge",
  "Stammdaten-Änderungsanträge bearbeiten",
  "Staplerschein läuft ab",
  "Straße / Hausnummer",
  "Stunden abziehen (−)",
  "Stunden gutschreiben (+)",
  "Stundenkorrektur buchen",
  "Stundenlohn (€)",
  "TGA · Zeitguthaben über 80 Stunden",
  "TP-Personalmanagement · Vorgesetztenplanung",
  "Tabellarische Schulungsübersicht",
  "Tabellarische Schulungsübersicht ·",
  "Teamübersicht",
  "Telefon Notfallkontakt",
  "Terminal / Hinweis",
  "Terminal angelegt",
  "Terminal konnte nicht angelegt werden.",
  "Terminal-App öffnen",
  "Terminal-Einrichtung auf diesem Gerät wirklich zurücksetzen?",
  "Terminalbeschreibung konnte nicht gespeichert werden.",
  "Terminalbeschreibung wurde gespeichert.",
  "Terminalstatus konnte nicht geändert werden.",
  "Terminalstatus wurde geändert.",
  "Textbaustein gespeichert.",
  "Textbausteine können jederzeit geladen und neu gespeichert werden.",
  "Titel / Betreff",
  "Transponder gesperrt",
  "Transponder konnte nicht gesperrt werden.",
  "Transponder sperren",
  "Unbez. Urlaub",
  "Urlaub & Abwesenheit",
  "Urlaub / Abwesenheit beantragen",
  "Urlaub / Gleittag",
  "Urlaub / Krankheit / sonstige Abwesenheit",
  "Urlaubsanspruch abzüglich genehmigter Urlaubstage im ausgewählten Jahr · ohne separaten Vorjahresübertrag.",
  "Urlaubsantrag gesendet.",
  "Urlaubsantrag zurückgezogen.",
  "Urlaubsanträge",
  "Urlaubsanträge freigeben",
  "Urlaubstag in Stunden umgewandelt",
  "Ursprünglich:",
  "Vergütung in die Historie übernommen.",
  "Vergütungshistorie",
  "Vergütungshistorie konnte nicht geladen werden.",
  "Vergütungshistorie wird geladen …",
  "Verträge, Bescheinigungen, Zeugnisse, Zertifikate und weitere Personaldokumente.",
  "Vorgegebener Arbeitsbeginn:",
  "Vorhandene Backups",
  "Vorhandene Gesellschaften und Logos",
  "Vorhandene Schulungen direkt anzeigen",
  "Vorhandene Terminals",
  "Was wird gesichert?",
  "Weitere Auswertungen",
  "Weitere Kennzahlen wie Schulungsquoten, Personalbewegungen und firmenbezogene Auswertungen können hier später ergänzt werden.",
  "Wichtige Personaldaten",
  "Wiederherstellung abgebrochen.",
  "Wochenplanung KW",
  "Wochenplanung konnte nicht geladen werden.",
  "Wochenplanung konnte nicht gespeichert werden.",
  "Wochenplanung wurde gespeichert.",
  "Zeiterfassung auf Projekte",
  "Zeiterfassungsanträge",
  "Zielgruppe Dashboard",
  "Zugeordnete Mitarbeiter",
  "Zuordnung prüfen",
  "Zuordnung und Bearbeitungsstand je Mitarbeiter für das gewählte Schulungsjahr",
  "Zur Kenntnis genommen",
  "Zur Sicherheit bitte das Wort WIEDERHERSTELLEN eingeben:",
  "aktive Benutzer vorhanden",
  "aktive Mitarbeiter",
  "aktuell zu bearbeiten",
  "angerechnet. Ein früherer echter KOMMEN-Zeitstempel bleibt zur Dokumentation sichtbar.",
  "anrechenbar ab  Uhr",
  "direkt zugeordnete Mitarbeiter",
  "eAU / Nachweis",
  "erforderlich / offen",
  "erst nach Gehen",
  "geprüft",
  "gesetzlich freiwillig",
  "gesetzlich pflichtversichert",
  "gültig / Auffrischung bis",
  "gültig bis",
  "heute fällig",
  "im System angelegt",
  "im sichtbaren Bereich",
  "interne Meldungen und E-Mail-Vorlagen verwalten.",
  "klicken. Das vorherige Projekt wird automatisch beendet.",
  "laufender Wert",
  "läuft",
  "nicht erforderlich",
  "noch zu bearbeiten",
  "offene Stammdaten-Änderungsantrag unter",
  "privat versichert",
  "protokollierte Vorgänge. Neueste Änderungen stehen oben.",
  "regelmäßig frei",
  "wartet/warten auf Kenntnisnahme.",
  "weitere Abwesenheit",
  "wird beim Export z. B.",
  "wurde angelegt.",
  "zurückgezogene Antrag",
  "·  Tage",
  "· Bereiche",
  "· aktueller Stand. Der Anteil oberhalb von 80:00 h ist als Auszahlungsmenge ausgewiesen.",
  "Änderung ohne Detailangabe.",
  "Änderungen",
  "Änderungsantrag senden",
  "Änderungsantrag wurde gesendet.",
  "Änderungsanträge",
  "Öffnen / Drucken",
  "Übernehmen",
  "Übernommen von",
  "Übersicht anzeigen",
  "Übertrag / Stundenkorrektur",
  "über 80 h",
  "–  ·  Tage",
  "–  ·  Tage · zurückgezogen",
  "– Vorlage auswählen –",
  "– auswählen –",
  "– keine Angabe –",
  "‹ Vorherige Woche",
  "← Vorheriger Monat",
  "⚠ Planung trotz Abwesenheit / freiem Tag",
  "⚠ Planung vorhanden"
]);
