import { db } from "./firebase.js";
import { collection, addDoc, getDocs, query, where, updateDoc, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js";
import { setHead } from "./app.js";
import { esc, fmtDate, statusPill, toast } from "./utils.js";
function workdays(a,b){let s=new Date(`${a}T12:00:00`),e=new Date(`${b}T12:00:00`),n=0;for(;s<=e;s.setDate(s.getDate()+1))if(s.getDay()!==0&&s.getDay()!==6)n++;return n}
export async function renderUrlaub(el,ctx){
  setHead("Urlaub & Abwesenheit","Urlaub beantragen, Abwesenheiten einsehen und Freigaben bearbeiten.");
  let own=[],team=[];try{const s=await getDocs(query(collection(db,"vacationRequests"),where("userId","==",ctx.profile.id)));own=s.docs.map(d=>({id:d.id,...d.data()}))}catch{}
  if(ctx.profile.role!=="employee"){try{const s=await getDocs(collection(db,"vacationRequests"));team=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>ctx.profile.role==="admin"||x.supervisorId===ctx.profile.id)}catch{}}
  const approved=own.filter(x=>x.status==="approved").reduce((a,x)=>a+Number(x.days||0),0),pending=own.filter(x=>x.status==="pending").reduce((a,x)=>a+Number(x.days||0),0);
  el.innerHTML=`<div class="kpi-grid three"><div class="kpi"><span>Anspruch</span><strong>${ctx.profile.vacationDays||30}</strong><small>Tage</small></div><div class="kpi"><span>Genehmigt</span><strong>${approved}</strong><small>Tage</small></div><div class="kpi"><span>Beantragt</span><strong>${pending}</strong><small>Tage</small></div></div>
    <div class="two-col"><article class="card"><div class="card-head"><div><h2>Urlaub beantragen</h2><p>Antrag wird dem zugeordneten Vorgesetzten bereitgestellt.</p></div></div><form id="vac-form" class="form-grid"><label class="field"><span>Von</span><input name="from" type="date" required></label><label class="field"><span>Bis</span><input name="to" type="date" required></label><label class="field"><span>Art</span><select name="type"><option>Urlaub</option><option>Freizeitausgleich</option><option>Sonderurlaub</option></select></label><label class="field"><span>Bemerkung</span><input name="note"></label><div class="field full"><button class="btn primary">Antrag senden</button></div></form></article>
    <article class="card"><div class="card-head"><div><h2>Meine Anträge</h2></div></div>${own.length?own.map(v=>`<div class="list-row"><div><strong>${fmtDate(v.from)} – ${fmtDate(v.to)}</strong><span>${esc(v.type||'Urlaub')} · ${v.days||0} Tage</span></div>${statusPill(v.status==='approved'?'Genehmigt':v.status==='rejected'?'Abgelehnt':'Beantragt',v.status==='approved'?'green':v.status==='rejected'?'red':'yellow')}</div>`).join(""):`<div class="empty">Keine Anträge vorhanden.</div>`}</article></div>
    ${ctx.profile.role!=="employee"?`<article class="card"><div class="card-head"><div><h2>Freigaben</h2><p>Urlaubsanträge der zugeordneten Mitarbeiter</p></div></div><div id="approval-list">${team.filter(v=>v.status==='pending').length?team.filter(v=>v.status==='pending').map(v=>`<div class="approval-row"><div><strong>${esc(v.userName||v.userId)}</strong><span>${fmtDate(v.from)} – ${fmtDate(v.to)} · ${v.days||0} Tage</span></div><div class="actions"><button class="btn small approve" data-id="${v.id}">Genehmigen</button><button class="btn small danger reject" data-id="${v.id}">Ablehnen</button></div></div>`).join(""):`<div class="empty">Keine offenen Freigaben.</div>`}</div></article>`:''}`;
  document.getElementById("vac-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),d=Object.fromEntries(f.entries());if(d.to<d.from){toast("Der Bis-Termin liegt vor dem Von-Termin.");return}await addDoc(collection(db,"vacationRequests"),{...d,days:workdays(d.from,d.to),userId:ctx.profile.id,userName:ctx.profile.name||ctx.profile.email,companyId:ctx.profile.companyId,supervisorId:ctx.profile.supervisorId||null,status:"pending",createdAt:serverTimestamp()});toast("Urlaubsantrag gesendet.");renderUrlaub(el,ctx)};
  el.querySelectorAll(".approve,.reject").forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,"vacationRequests",b.dataset.id),{status:b.classList.contains("approve")?"approved":"rejected",decidedBy:ctx.profile.id,decidedAt:serverTimestamp()});toast("Antrag bearbeitet.");renderUrlaub(el,ctx)})
}
